---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cbtsmpam/absensi/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
    
    # Public Folder Handling (Exclude excess files)
    - /bin/mkdir -p $DEPLOYPATH/public
    - /bin/cp -R public/build $DEPLOYPATH/public/
    - /bin/cp public/index.php $DEPLOYPATH/public/
    - /bin/cp public/.htaccess $DEPLOYPATH/public/
    - /bin/cp public/favicon.ico $DEPLOYPATH/public/
    - /bin/cp public/robots.txt $DEPLOYPATH/public/
    - /bin/cp -R public/assets $DEPLOYPATH/public/
    - /bin/cp -R public/fonts $DEPLOYPATH/public/
    - /bin/cp -R public/templates_card $DEPLOYPATH/public/
